services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: app.dockerfile
    networks:
      - builder-network
    depends_on:
      - database
    ports:
      - "5173:5173"
    environment:
      - VITE_URL_API_BASE=
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:3000"
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - builder-network

networks:
  builder-network:
    driver: bridge

